name: Update Submodule and Build

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-existing-action]


jobs:
  update_and_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # Use this token for checkout
        
    - name: Commit and Push Changes
      run: |
        pwd
        ls
        git config --global user.name 'DrewBot'
        git config --global user.email 'drewbot@example.com'

        cat .gitmodules
        git submodule status
        echo 'attempting to update submodules now'
        git submodule update --init --recursive
        git submodule update --remote --merge

        cat .gitmodules
        git submodule status
        echo 'adding'
        git add -A
        echo 'committing'
        git commit -m "Update submodules"
        echo 'pushing'
        git push
